config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users do
    member do
      post :pay
      post :subscribe
    end
  end

  resource :sessions do
    member do
      get :destroy, as: 'destroy'
    end
  end

  # Stripe Connect endpoints
  #  - oauth flow
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  #  - create accounts
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  post '/connect/standalone' => 'stripe#standalone', as: 'stripe_standalone'

  # Stripe webhooks
  post '/hooks/stripe' => 'hooks#stripe'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  serialize :stripe_account_status, JSON
  has_secure_password

  # General 'has a Stripe account' check
  def connected?; !stripe_user_id.nil?; end

  # Stripe account type checks
  def managed?; stripe_account_type == 'managed'; end
  def standalone?; stripe_account_type == 'standalone'; end
  def oauth?; stripe_account_type == 'oauth'; end

  def manager
    case stripe_account_type
    when 'managed' then StripeManaged.new(self)
    when 'standalone' then StripeStandalone.new(self)
    when 'oauth' then StripeOauth.new(self)
    end
  end

  def can_accept_charges?
    return true if oauth?
    return true if managed? && stripe_account_status['charges_enabled']
    return true if standalone? && stripe_account_status['charges_enabled']
    return false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Most actions here need a logged in user.
  # ApplicationHelper#current_user will return the logged in user.
  before_action :require_user, except: %w{ new create }

  # A list of all users in the database.
  # app/views/users/index.html.haml
  def index
    @users = User.all
  end

  # A signup form.
  # app/views/users/new.html.haml
  def new
    @user = User.new
  end

  # Create a new user via #new
  # Log them in after creation, and take
  # them to their own 'profile page'.
  def create
    @user = User.create( user_params )
    session[:user_id] = @user.id
    if @user.valid?
      redirect_to user_path( @user )
    else
      render action: 'new'
    end
  end

  def update
    manager = current_user.manager
    manager.update_account! params: params
    redirect_to user_path( current_user )
  end

  # Show a user's profile page.
  # This is where you can spend money with the connected account.
  # app/views/users/show.html.haml
  def show
    @user = User.find( params[:id] )
    @plans = Stripe::Plan.all
  end

  # Make a one-off payment to the user.
  # See app/assets/javascripts/app/pay.coffee
  def pay
    # Find the user to pay.
    user = User.find( params[:id] )

    # Charge $10.
    amount = 1000
    # Calculate the fee amount that goes to the application.
    fee = (amount * Rails.application.secrets.fee_percentage).to_i

    begin
      charge_attrs = {
        amount: amount,
        currency: user.currency,
        source: params[:token],
        description: "Test Charge via Stripe Connect",
        application_fee: fee
      }

      case params[:charge_on]
      when 'connected'
        # Use the user-to-be-paid's access token
        # to make the charge directly on their account
        charge = Stripe::Charge.create( charge_attrs, user.secret_key )
      when 'platform'
        # Use the platform's access token, and specify the
        # connected account's user id as the destination so that
        # the charge is transferred to their account.
        charge_attrs[:destination] = user.stripe_user_id
        charge = Stripe::Charge.create( charge_attrs )
      end

      flash[:notice] = "Charged successfully! <a target='_blank' rel='#{params[:charge_on]}-account' href='https://dashboard.stripe.com/test/payments/#{charge.id}'>View in dashboard &raquo;</a>"

    rescue Stripe::CardError => e
      error = e.json_body[:error][:message]
      flash[:error] = "Charge failed! #{error}"
    end

    redirect_to user_path( user )
  end

  # Subscribe the currently logged in user to
  # a plan owned by the application.
  # See app/assets/javascripts/app/subscribe.coffee
  def subscribe
    # Find the user to pay.
    user = User.find( params[:id] )

    # Calculate the fee percentage that applies to
    # all invoices for this subscription.
    fee_percent = (Rails.application.secrets.fee_percentage * 100).to_i
    begin
      # Create a customer and subscribe them to a plan
      # in one shot.
      # Normally after this you would store customer.id
      # in your database so that you can keep track of
      # the subscription status/etc. Here we're just
      # fire-and-forgetting it.
      customer = Stripe::Customer.create(
        {
          source: params[:token],
          email: current_user.email,
          plan: params[:plan],
          application_fee_percent: fee_percent
        },
        user.secret_key
      )
      flash[:notice] = "Subscribed! <a target='_blank' rel='platform-account' href='https://dashboard.stripe.com/test/customers/#{customer.id}'>View in dashboard &raquo;</a>"

    rescue Stripe::CardError => e
      error = e.json_body[:error][:message]
      flash[:error] = "Charge failed! #{error}"
    end

    redirect_to user_path( user )
  end

  private

  def user_params
    p = params.require(:new_user).permit( :name, :email, :password )
    p[:email].downcase!
    p
  end

end

app/views/users/_connect.html.haml
.panel.panel-primary
  .panel-body
    %h3 Connect
    %p There are 3 ways to create/connect your Stripe account.

    %ul.list-group
      %li.list-group-item#stripe-oauth
        %a.pull-right.btn.btn-lg.btn-primary{ href: stripe_oauth_path } Connect
        %h3 OAuth
        %p Connect or create a Stripe account via OAuth.

      %li.list-group-item#stripe-standalone
        = form_tag stripe_standalone_path, method: 'POST' do
          %input.pull-right.btn.btn-lg.btn-primary{ type: 'submit', value: 'Create' }
          %h3 Standalone
          %p
            %small Create a standalone Stripe account in
            %select.country{ name: 'country' }
              - StripeStandalone::COUNTRIES.each do |country|
                %option{ value: country[:code] }= country[:name]

      - # managed accounts are in public beta
      - # see services/stripe_managed.rb#ALLOWED
      - if Stripe::Account.retrieve('self').country.in? StripeManaged::ALLOWED
        %li.list-group-item#stripe-managed
          = form_tag stripe_managed_path, method: 'POST' do
            %input.pull-right.btn.btn-lg.disabled.btn-primary{ type: 'submit', value: 'Create' }
            %h3 Managed
            %p
              %small Create a managed Stripe account in
              %select.country{ name: 'country' }
                - StripeManaged::COUNTRIES.each do |country|
                  %option{ value: country[:code] }= country[:name]
              %br
              %label.tos
                %input{ type: 'checkbox', name: 'tos', checked: false }
                I accept the
                %a{ href: 'https://stripe.com/us/terms', target: '_blank' } Stripe Terms of Service

app/views/users/_nav.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: '#navbar-links' } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %p.navbar-text
        %span.glyphicon.glyphicon-chevron-right
        %span.hidden-xs Logged in as
        %a{ href: user_path( current_user ) }
          %strong= current_user.name

    .collapse.navbar-collapse{ id: 'navbar-links' }
      %p.navbar-text.navbar-right
        - if request.path == users_path
          All Users
        - else
          %a.navbar-link{ href: users_path } All Users
        %span.sep &nbsp;|&nbsp;
        %a.navbar-link{ href: destroy_sessions_path } Logout

app/views/users/_pay.html.haml
- if @user.can_accept_charges?
  .panel.panel-primary
    .panel-body
      = form_tag pay_user_path( @user ) do
        .indicator
        = hidden_field_tag :token
        %button.pull-right.btn.btn-primary.btn-lg.pay-button Pay $10

        %h3 Make a one-off charge
        %p
          Pay a one-time charge of $10 #{@user.currency.upcase}.
        %p
          %small Responsible for fees, refunds and chargebacks?
          %select{ name: 'charge_on' }
            %option{ value: 'connected' } Connected Account
            %option{ value: 'platform' } Platform Account

  .panel.panel-primary
    .panel-body
      = form_tag subscribe_user_path( @user ) do
        .indicator
        = hidden_field_tag :token
        = hidden_field_tag :plan
        %button.pull-right.btn.btn-primary.btn-lg.subscribe-button{ disabled: true } Subscribe

        %h3 Subscribe to a plan
        %p
          - if @plans.any?
            The application defines the following plans:
          - else
            The application has no plans.
            %a{ href: 'https://dashboard.stripe.com/test/plans', rel: 'platform-account', target: '_blank' } Add Plans &raquo;
        - if @plans.any?
          .list-group
            - @plans.each do |plan|
              %a.list-group-item.plan-choice{ data: plan.to_hash }
                = plan.name
                \-
                %strong
                  = number_to_currency( plan.amount / 100 )
                  = plan.currency.upcase
          %p
            %small Responsible for fees, refunds and chargebacks?
            %select{ name: 'charge_on', disabled: true }
              %option{ value: 'connected' } Connected Account
              - # charging on the platform is currently not
              - # supported for subscriptions
              - # %option{ value: 'platform' } Platform Account

- else
  .panel.panel-danger
    .panel-body
      %h3 Nope

= javascript_include_tag 'https://checkout.stripe.com/checkout.js'
:javascript
  // You can select to pay either directly or via the platform, so
  // we need both publishable keys here.
  window.publishable = {
    platform: #{Rails.application.secrets.stripe_publishable_key.to_json},
    connected: #{@user.publishable_key.to_json}
  };
  window.currentUserEmail = #{current_user.email.to_json};
  window.payPath = #{pay_user_path( @user ).to_json};

app/views/users/_settings.html.haml
.panel.panel-primary
  .panel-body
    - if current_user.oauth?
      %a.pull-right.btn.btn-danger.btn-lg{ href: stripe_deauthorize_path } Deauthorize
      %h3 Disconnect
      %p
        Since this is you, you can
        %br
        disconnect from this application.

    - if current_user.managed?
      %h2 Stripe Account Management
      %p
        Account Type:
        %strong Managed

      - # the current account status, whether the
      - # account can make charges or can receive transfers
      %p
        .account-status
          Status:
          - charges = [ 'Charges', @user.stripe_account_status['charges_enabled'] ]
          - transfers = [ 'Transfers', @user.stripe_account_status['transfers_enabled'] ]
          %table
            - [ charges, transfers ].each do |text, yn|
              %tr
                %td
                  %span.label{ class: yn ? 'label-primary' : 'label-danger' }
                    %span.glyphicon{ class: yn ? 'glyphicon-ok' : 'glyphicon-remove' }
                    = text

      - # if we need more information from this user to keep
      - # their account in good standing
      - if @user.stripe_account_status['fields_needed'].any?
        %hr
        .needed
          = form_for @user, html: { class: 'form-horizontal' } do |f|
            %h3 Needed Information
            - if @user.stripe_account_status['due_by']
              %p
                Due by:
                %strong= Time.at( @user.stripe_account_status['due_by'] ).strftime("%Y-%m-%d")

            - if params[:debug]
              = debug @user.stripe_account_status['fields_needed']

            - manager = StripeManaged.new( current_user )
            %ul.list-group

              - # this account needs a bank account
              - if manager.needs? 'bank_account'
                %li.list-group-item#bank-account{ data: { publishable: @user.publishable_key } }
                  %script{ src: 'https://js.stripe.com/v2/' }
                  %h3 Bank Account
                  = hidden_field_tag :bank_account_token
                  .form-group
                    - countries = manager.supported_bank_account_countries
                    %label.control-label.col-xs-12.col-sm-3 Country:
                    .col-xs-12.col-sm-9
                      %select.form-control{ data: { stripe: 'country' } }
                        - countries.each do |country|
                          %option{ value: country[:code] }= country[:name]
                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Account Number:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', data: { stripe: 'account_number' } }
                  .form-group#bank-routing-container
                    %label.control-label.col-xs-12.col-sm-3 Routing Number:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', data: { stripe: 'routing_number' } }

              - # this account needs legal entity info
              - if manager.needs? 'legal_entity.'
                %li.list-group-item
                  %h3 Legal Entity
                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 First Name:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[first_name]', value: manager.legal_entity.first_name }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Last Name:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[last_name]', value: manager.legal_entity.last_name }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Date of Birth:
                    .col-xs-12.col-sm-9
                      - dob = manager.legal_entity.dob
                      - selected = Date.new( dob.year, dob.month, dob.day ) rescue nil
                      = date_select 'legal_entity', 'dob',
                          { selected: selected,
                            prompt: true,
                            start_year: 90.years.ago.year,
                            end_year: 13.years.ago.year },
                          { class: 'form-control' }

                  - if manager.needs? 'legal_entity.personal_id_number'
                    .form-group
                      %label.control-label.col-xs-12.col-sm-3 Personal ID Number:
                      .col-xs-12.col-sm-9
                        %input.form-control{ type: 'text', name: 'legal_entity[personal_id_number]' }
                  - elsif manager.needs? 'legal_entity.ssn_last_4'
                    .form-group
                      %label.control-label.col-xs-12.col-sm-3 SSN Last 4:
                      .col-xs-12.col-sm-9
                        %input.form-control{ type: 'text', name: 'legal_entity[ssn_last_4]' }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Address Line 1:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][line1]', value: manager.legal_entity.address.line1 }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Address Line 2:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][line2]', value: manager.legal_entity.address.line2 }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 City:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][city]', value: manager.legal_entity.address.city }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 State/Province:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][state]', value: manager.legal_entity.address.state }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 ZIP/Postal Code:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: "legal_entity[address][postal_code]", value: manager.legal_entity.address.postal_code }


            %br
            .buttons
              = f.submit 'Save Info', class: 'btn btn-lg btn-primary'

    - if current_user.standalone?
      %h3 Stripe Account Management
      %p
        Account Type:
        %strong Standalone

      - # the current account status, whether the
      - # account can make charges or can receive transfers
      %p
        .account-status
          Status:
          - charges = [ 'Charges', @user.stripe_account_status['charges_enabled'] ]
          - transfers = [ 'Transfers', @user.stripe_account_status['transfers_enabled'] ]
          %table
            - [ charges, transfers ].each do |text, yn|
              %tr
                %td
                  %span.label{ class: yn ? 'label-primary' : 'label-danger' }
                    %span.glyphicon{ class: yn ? 'glyphicon-ok' : 'glyphicon-remove' }
                    = text
      - unless @user.stripe_account_status['details_submitted']
        %hr
        %ul.list-group
          %li.list-group-item
            %a.btn.btn-primary.btn-lg.pull-right{ href: 'https://dashboard.stripe.com/account/details' }
              %span.glyphicon.glyphicon-arrow-right
            %h3 Claim or activate your account.
            %p
              You will also receive a link from Stripe via email.

app/views/users/index.html.haml
.col-md-6.col-md-offset-3.col-xs-12
  = render partial: 'nav'

  %h1 Users

  %br

  .list-group.users
    - @users.each do |user|
      .list-group-item{ class: ('active' if user == current_user), href: user_path( user ) }
        .pull-right.nudge-small-text
          %small
            %a{ target: '_blank', rel: 'platform-account', href: "https://dashboard.stripe.com/test/applications/users/#{user.stripe_user_id}" }= user.stripe_user_id
        %a{ href: user_path( user ) }
          %strong= user.name
          %span.nowrap (#{user.email})

app/views/users/new.html.haml
%br
.col-md-4.col-md-offset-4.col-xs-12
  .panel.panel-primary
    .panel-body
      = form_for @user, as: 'new_user', html: { class: 'form-horizontal' } do |f|
        %h2 New User
        - if @user.errors.any?
          .alert.alert-danger
            %strong Found some problems :(
            %ul
              - @user.errors.full_messages.each do |msg|
                %li= msg

        .form-group
          = f.label :name, class: 'col-xs-3 control-label'
          .col-xs-9
            = f.text_field :name, class: 'form-control', placeholder: 'Your Name'
        .form-group
          = f.label :email, class: 'col-xs-3 control-label'
          .col-xs-9
            = f.email_field :email, class: 'form-control', placeholder: 'your@email.com'
        .form-group
          = f.label :password, class: 'col-xs-3 control-label'
          .col-xs-9
            = f.password_field :password, class: 'form-control', placeholder: ('&bull;' * 16).html_safe

        %button.btn.btn-primary.main-button{ type: 'submit' } Signup

app/views/users/show.html.haml
.col-md-6.col-md-offset-3.col-xs-12
  = render partial: 'nav'

  - if flash[:notice]
    .alert.alert-info
      %p= flash[:notice].html_safe
  - if flash[:error]
    .alert.alert-danger
      %p= flash[:error].html_safe

  %h1= @user.name
  %h4= @user.email

  - if @user.connected?
    - if is_myself?
      - # you're looking at your own 'profile', so you can
      - # update/deauthorize/etc your Stripe account
      = render partial: 'settings'
    - else
      = render partial: 'pay'

  - else
    - if is_myself? && !current_user.connected?
      - # you're looking at your own 'profile', so you can
      - # create/connect/etc your Stripe account
      = render partial: 'connect'
    - else
      .panel.panel-danger.not-connected
        .panel-body
          %h3 Not Connected
          %p
            This user is not connected to Stripe, so
            you can't pay them.